"""
HTTP Stress tests with NGINX in place of Tempesta FW - to compare results.
"""

__author__ = "Tempesta Technologies, Inc."
__copyright__ = "Copyright (C) 2022 Tempesta Technologies, Inc."
__license__ = "GPL2"

from t_stress.test_stress import BaseCurlStress, TlsWrkStress, WrkStress


# Config to start Nginx instead of Tempesta on 80 and 443 ports
NGINX_PROXY_CONFIG = """
pid ${pid};
worker_processes  auto;
events {
    worker_connections   1024;
    use epoll;
}
http {
    keepalive_timeout ${server_keepalive_timeout};
    keepalive_requests ${server_keepalive_requests};
    sendfile         on;
    tcp_nopush       on;
    tcp_nodelay      on;
    open_file_cache max=1000;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors off;
    error_log /dev/null emerg;
    access_log off;
    server {
        listen 80;
        listen 443 ssl http2;
        server_name tempesta-tech.com;
        ssl_certificate ${tempesta_workdir}/tempesta.crt;
        ssl_certificate_key ${tempesta_workdir}/tempesta.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!MD5;
        location / {
            proxy_pass http://${server_ip}:8000;
        }
        location /nginx_status {
            stub_status on;
        }
    }
}
"""


class NginxProxyMixin:
    """
    Mixin to run Nginx instead of Tempesta in tests,
    to compare the result with Tempesta under the same circumstances.
    """

    def setUp(self):
        self.backends = [
            *self.backends[:],
            {
                "id": "nginx",
                "type": "nginx",
                "port": "80",
                "status_uri": "http://${server_ip}:80/nginx_status",
                "config": NGINX_PROXY_CONFIG,
            },
        ]
        super().setUp()

    def start_all(self):
        # Start servers, but not Tempesta
        self.start_all_servers()
        self.deproxy_manager.start()


class NginxWrkStress(NginxProxyMixin, WrkStress):
    """Nginx HTTP stress test generated by `wrk` with concurrent connections."""


class NginxTlsWrkStress(NginxProxyMixin, TlsWrkStress):
    """Nginx HTTPS stress test generated by `wrk` with concurrent connections."""


class NginxCurlStress(NginxProxyMixin, BaseCurlStress):
    """Nginx HTTP stress test generated by `curl`."""

    proto = "http"


class NginxTlsCurlStress(NginxProxyMixin, BaseCurlStress):
    """Nginx HTTPS stress test generated by `curl`."""

    proto = "https"

    def setUp(self):
        self.clients = [{**client, "ssl": True} for client in self.clients]
        super().setUp()


class NginxH2CurlStress(NginxProxyMixin, BaseCurlStress):
    """Nginx HTTP/2 stress test generated by `curl`."""

    proto = "h2"

    def setUp(self):
        self.clients = [{**client, "http2": True} for client in self.clients]
        super().setUp()
