[pytest]
minversion = 9.0
testpaths = tests
python_files = test_*.py
log_cli = true
log_level = CRITICAL
addopts =
    -ra
    --strict-markers
    --strict-config
    --disable-warnings
    -sv

markers =
    flaky(reruns): rerun test up to `reruns` times if it fails;
