"""
Custom error page generator.

Tempesta administrator can specify files with page bodies for error responses
generated by Tempesta FW.
"""

from framework.helpers import tf_cfg

__author__ = "Tempesta Technologies, Inc."
__copyright__ = "Copyright (C) 2023 Tempesta Technologies, Inc."
__license__ = "GPL2"


class CustomErrorPageGenerator(object):
    def __init__(self, data, f_path=None, default=False):
        workdir = tf_cfg.cfg.get("Tempesta", "workdir")
        self.f_path = f_path if f_path else workdir + "/tempesta.html"
        self.data = data
        if default:
            self.generate()

    @staticmethod
    def __write(path, data):
        with open(path, "wt") as fdesc:
            fdesc.write(data)

    def generate(self):
        self.__write(self.f_path, self.data)

    def __str__(self):
        assert self.data, "Stringify null custom error page object"
        return self.data

    def get_file_path(self):
        return self.f_path
